# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fragment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fragment.proto',
  package='ofl',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x66ragment.proto\x12\x03ofl\"\xe1\x02\n\x07Metrics\x12\x1a\n\x12train_acc_fragment\x18\x01 \x01(\x02\x12\x1b\n\x13train_loss_fragment\x18\x02 \x01(\x02\x12\x19\n\x11train_tp_fragment\x18\x03 \x03(\x05\x12\x19\n\x11train_tn_fragment\x18\x04 \x03(\x05\x12\x19\n\x11train_fp_fragment\x18\x05 \x03(\x05\x12\x19\n\x11train_fn_fragment\x18\x06 \x03(\x05\x12\x19\n\x11test_acc_fragment\x18\x07 \x01(\x02\x12\x1a\n\x12test_loss_fragment\x18\x08 \x01(\x02\x12\x18\n\x10test_tp_fragment\x18\t \x03(\x05\x12\x18\n\x10test_tn_fragment\x18\n \x03(\x05\x12\x18\n\x10test_fp_fragment\x18\x0b \x03(\x05\x12\x18\n\x10test_fn_fragment\x18\x0c \x03(\x05\x12\x12\n\nthresholds\x18\r \x01(\x05\"+\n\x05Model\x12\x11\n\tframework\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\xae\x01\n\x08\x46ragment\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x16\n\x0etraining_round\x18\x02 \x01(\x05\x12\x1f\n\x17local_train_sample_size\x18\x03 \x01(\x05\x12\x1e\n\x16local_test_sample_size\x18\x04 \x01(\x05\x12\x19\n\x05model\x18\x05 \x01(\x0b\x32\n.ofl.Model\x12\x1d\n\x07metrics\x18\x06 \x01(\x0b\x32\x0c.ofl.Metricsb\x06proto3')
)




_METRICS = _descriptor.Descriptor(
  name='Metrics',
  full_name='ofl.Metrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_acc_fragment', full_name='ofl.Metrics.train_acc_fragment', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_loss_fragment', full_name='ofl.Metrics.train_loss_fragment', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_tp_fragment', full_name='ofl.Metrics.train_tp_fragment', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_tn_fragment', full_name='ofl.Metrics.train_tn_fragment', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_fp_fragment', full_name='ofl.Metrics.train_fp_fragment', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_fn_fragment', full_name='ofl.Metrics.train_fn_fragment', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_acc_fragment', full_name='ofl.Metrics.test_acc_fragment', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_loss_fragment', full_name='ofl.Metrics.test_loss_fragment', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_tp_fragment', full_name='ofl.Metrics.test_tp_fragment', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_tn_fragment', full_name='ofl.Metrics.test_tn_fragment', index=9,
      number=10, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_fp_fragment', full_name='ofl.Metrics.test_fp_fragment', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_fn_fragment', full_name='ofl.Metrics.test_fn_fragment', index=11,
      number=12, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thresholds', full_name='ofl.Metrics.thresholds', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=377,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='ofl.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='framework', full_name='ofl.Model.framework', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='ofl.Model.payload', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=422,
)


_FRAGMENT = _descriptor.Descriptor(
  name='Fragment',
  full_name='ofl.Fragment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ofl.Fragment.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training_round', full_name='ofl.Fragment.training_round', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_train_sample_size', full_name='ofl.Fragment.local_train_sample_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_test_sample_size', full_name='ofl.Fragment.local_test_sample_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='ofl.Fragment.model', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='ofl.Fragment.metrics', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=599,
)

_FRAGMENT.fields_by_name['model'].message_type = _MODEL
_FRAGMENT.fields_by_name['metrics'].message_type = _METRICS
DESCRIPTOR.message_types_by_name['Metrics'] = _METRICS
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['Fragment'] = _FRAGMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Metrics = _reflection.GeneratedProtocolMessageType('Metrics', (_message.Message,), dict(
  DESCRIPTOR = _METRICS,
  __module__ = 'fragment_pb2'
  # @@protoc_insertion_point(class_scope:ofl.Metrics)
  ))
_sym_db.RegisterMessage(Metrics)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'fragment_pb2'
  # @@protoc_insertion_point(class_scope:ofl.Model)
  ))
_sym_db.RegisterMessage(Model)

Fragment = _reflection.GeneratedProtocolMessageType('Fragment', (_message.Message,), dict(
  DESCRIPTOR = _FRAGMENT,
  __module__ = 'fragment_pb2'
  # @@protoc_insertion_point(class_scope:ofl.Fragment)
  ))
_sym_db.RegisterMessage(Fragment)


# @@protoc_insertion_point(module_scope)
