# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import taskService_pb2 as taskService__pb2


class PerformanceMgrStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.commitJob = channel.unary_unary(
                '/PerformanceMgr/commitJob',
                request_serializer=taskService__pb2.TaskConfig.SerializeToString,
                response_deserializer=taskService__pb2.OperationStatus.FromString,
                )


class PerformanceMgrServicer(object):
    """Missing associated documentation comment in .proto file."""

    def commitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerformanceMgrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'commitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.commitJob,
                    request_deserializer=taskService__pb2.TaskConfig.FromString,
                    response_serializer=taskService__pb2.OperationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PerformanceMgr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PerformanceMgr(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def commitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PerformanceMgr/commitJob',
            taskService__pb2.TaskConfig.SerializeToString,
            taskService__pb2.OperationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
