# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: performanceService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import taskService_pb2 as taskService__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18performanceService.proto\x1a\x11taskService.proto2<\n\x0ePerformanceMgr\x12*\n\tcommitJob\x12\x0b.TaskConfig\x1a\x10.OperationStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'performanceService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PERFORMANCEMGR']._serialized_start=47
  _globals['_PERFORMANCEMGR']._serialized_end=107
# @@protoc_insertion_point(module_scope)
