# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rayclusterService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17rayclusterService.proto\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x15RayClusterActResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\";\n\x0fRayClusterParam\x12\x15\n\rk8s_namespace\x18\x01 \x01(\t\x12\x11\n\tray_label\x18\x02 \x01(\t\"*\n\x15RayClusterQueryResult\x12\x11\n\tjson_data\x18\x01 \x01(\t\"\xa6\x01\n\x15RayClusterModifyParam\x12\x15\n\rk8s_namespace\x18\x01 \x01(\t\x12\x10\n\x08ray_name\x18\x02 \x01(\t\x12\x11\n\tray_label\x18\x03 \x01(\t\x12\x1b\n\x13worker_min_replicas\x18\x04 \x01(\x05\x12\x17\n\x0fworker_replicas\x18\x05 \x01(\x05\x12\x1b\n\x13worker_max_replicas\x18\x06 \x01(\x05\x32\x92\x02\n\rRayClusterMgr\x12\x42\n\x10\x63reateRayCluster\x12\x16.google.protobuf.Empty\x1a\x16.RayClusterActResponse\x12<\n\x10\x64\x65leteRayCluster\x12\x10.RayClusterParam\x1a\x16.RayClusterActResponse\x12\x42\n\x10modifyRayCluster\x12\x16.RayClusterModifyParam\x1a\x16.RayClusterActResponse\x12;\n\x0fqueryRayCluster\x12\x10.RayClusterParam\x1a\x16.RayClusterQueryResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rayclusterService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAYCLUSTERACTRESPONSE._serialized_start=56
  _RAYCLUSTERACTRESPONSE._serialized_end=91
  _RAYCLUSTERPARAM._serialized_start=93
  _RAYCLUSTERPARAM._serialized_end=152
  _RAYCLUSTERQUERYRESULT._serialized_start=154
  _RAYCLUSTERQUERYRESULT._serialized_end=196
  _RAYCLUSTERMODIFYPARAM._serialized_start=199
  _RAYCLUSTERMODIFYPARAM._serialized_end=365
  _RAYCLUSTERMGR._serialized_start=368
  _RAYCLUSTERMGR._serialized_end=642
# @@protoc_insertion_point(module_scope)
